<?php

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/tenancy-debug', function () {
    return response()->json([
        'is_central'      => !tenancy()->initialized,
        'tenant_id'       => tenancy()->tenant?->id ?? null,
        'central_domains' => config('tenancy.central_domains'),
        'current_host'    => request()->getHost(),
    ]);
});

/**
 * Superadmin impersonation: logs in as a tenant admin user.
 * URL is time-limited and signed — generated by the SaasClientResource action.
 */
Route::get('/preview/company-logo/{companyLogo}', [App\Http\Controllers\DocumentsController::class, 'previewCompanyLogo'])
    ->name('preview.company-logo');

Route::get('/admin/impersonate/{userId}/{slug}', function (Request $request, string $userId, string $slug) {
    abort_unless($request->hasValidSignature(), 403);

    $user = User::withoutGlobalScopes()->findOrFail($userId);

    // Log in on the web guard as the tenant user
    Auth::guard('web')->loginUsingId($userId);

    // Redirect to the tenant's Filament app panel
    // URL structure: /app (panel path) + /app (tenantRoutePrefix) + /{slug}
    return redirect("/app/app/{$slug}");
})->name('admin.impersonate');
