<?php

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/tenancy-debug', function () {
    return response()->json([
        'is_central'      => !tenancy()->initialized,
        'tenant_id'       => tenancy()->tenant?->id ?? null,
        'central_domains' => config('tenancy.central_domains'),
        'current_host'    => request()->getHost(),
    ]);
});

/**
 * Superadmin impersonation: logs in as a tenant admin user.
 * URL is time-limited and signed — generated by the SaasClientResource action.
 */
Route::get('/preview/company-logo/{companyLogo}', [App\Http\Controllers\DocumentsController::class, 'previewCompanyLogo'])
    ->name('preview.company-logo');

Route::get('/preview/invoice/{invoice}', [App\Http\Controllers\DocumentsController::class, 'previewInvoice'])
    ->name('preview.invoice');

Route::get('/preview/manual-invoice/{manualInvoice}', [App\Http\Controllers\DocumentsController::class, 'previewManualInvoice'])
    ->name('preview.manual-invoice');

Route::get('/preview/credit-note/{creditNote}', [App\Http\Controllers\DocumentsController::class, 'previewCreditNote'])
    ->name('preview.credit-note');

Route::get('/preview/receipt/{receipt}', [App\Http\Controllers\DocumentsController::class, 'previewReceipt'])
    ->name('preview.receipt');

Route::get('/admin/impersonate/{userId}/{slug}', function (Request $request, string $userId, string $slug) {
    abort_unless($request->hasValidSignature(), 403);

    $user = User::withoutGlobalScopes()->findOrFail($userId);

    // Log in on the web guard as the tenant user
    Auth::guard('web')->loginUsingId($userId);

    // Redirect to the tenant's Filament app panel — URL: /app/{slug}
    return redirect("/app/{$slug}");
})->name('admin.impersonate');
