<?php

namespace App\Filament\Pages;

use App\Models\CreditNote;
use App\Models\Invoice;
use App\Models\InvoicePayment;
use App\Models\Property;
use Carbon\Carbon;
use Filament\Forms\Components\Card;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\MultiSelect;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class AgeingSummaryReport extends Page implements HasForms
{
    use InteractsWithForms;

    public $property;
    public $zero_to_thirty_days = false;
    public $thirty_one_to_sixty_days = false;
    public $sixty_one_to_ninety_days = false;
    public $over_ninety_days = false;

    public $statementPath;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.ageing-summary-report';

    public ?array $generateReportForm = [];

    public function render(): View
    {
        $this->form->fill();
        return parent::render(); // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        $form->schema([
            // ...
            Select::make('property')
                ->label('Property')
                ->options(Property::query()->select(['id','name'])->get()->pluck('name','id')),
            Section::make('ranges-section')
                ->heading('Ranges *')
                ->description('Tick the periods to include in the report')
                ->schema([
                    Checkbox::make('zero_to_thirty_days')
                        ->label('0-30 days'),
                    Checkbox::make('thirty_one_to_sixty_days')
                        ->label('31-60 days'),
                    Checkbox::make('sixty_one_to_ninety_days')
                        ->label('61-90 days'),
                    Checkbox::make('over_ninety_days')
                        ->label('Over 90 days'),
                ]),
        ])->statePath('generateReportForm');

        return $form;
    }

    public array $rules = [
        'property' => ['required'],
        'zero_to_thirty_days' => ['required'],
        'thirty_one_to_sixty_days' => ['required'],
        'sixty_one_to_ninety_days' => ['required'],
        'over_ninety_days' => ['required'],
    ];

    public array $messages = [
        'property.required' => 'Please select a property',
        'zero_to_thirty_days.required' => 'Please select at least one range',
        'thirty_one_to_sixty_days.required' => 'Please select at least one range',
        'sixty_one_to_ninety_days.required' => 'Please select at least one range',
        'over_ninety_days.required' => 'Please select at least one range',
    ];

    public function submitGenerateReportForm()
    {
        $submittedFormData = $this->form->getState();

        $this->customValidate($submittedFormData);

        return response()->download($this->statementPath);
    }

    public function customValidate($submittedFormData)
    {
        $rules = [
            'property' => ['nullable'],
            'zero_to_thirty_days' => ['nullable'],
            'thirty_one_to_sixty_days' => ['nullable'],
            'sixty_one_to_ninety_days' => ['nullable'],
            'over_ninety_days' => ['nullable'],
        ];

        $messages = [
            'property.required' => 'Please select a property',
            'zero_to_thirty_days.required' => 'Please select at least one range',
            'thirty_one_to_sixty_days.required' => 'Please select at least one range',
            'sixty_one_to_ninety_days.required' => 'Please select at least one range',
            'Over_ninety_days.required' => 'Please select at least one range',
        ];

        $validator = Validator::make($submittedFormData, $rules, $messages);

        // ensure at least one range is selected (set to true)
        $atLeastOneRangeSelected = false;
        if ($submittedFormData['zero_to_thirty_days']) {
            $atLeastOneRangeSelected = true;
        }else if ($submittedFormData['thirty_one_to_sixty_days']) {
            $atLeastOneRangeSelected = true;
        }else if ($submittedFormData['sixty_one_to_ninety_days']) {
            $atLeastOneRangeSelected = true;
        }else if ($submittedFormData['over_ninety_days']) {
            $atLeastOneRangeSelected = true;
        }

        if (!$atLeastOneRangeSelected){
            $this->displayErrorNotification('Please select at least one range');
            return false;
        }

        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                $this->displayErrorNotification($error);
            }
            return false;
        }

        // get the validated data
        $this->property = $submittedFormData['property'];
        $this->zero_to_thirty_days = $submittedFormData['zero_to_thirty_days'];
        $this->thirty_one_to_sixty_days = $submittedFormData['thirty_one_to_sixty_days'];
        $this->sixty_one_to_ninety_days = $submittedFormData['sixty_one_to_ninety_days'];
        $this->over_ninety_days = $submittedFormData['over_ninety_days'];

        $outputText = '';

        // select all tenancy agreements for the property
        if ($this->property){
            $propertyTotalDue = 0;
            $propertyOneToThirtyPastDue = 0;
            $propertyThirtyOneToSixtyPastDue = 0;
            $propertySixtyOneToNinetyPastDue = 0;
            $propertyOverNinetyPastDue = 0;

            $property = Property::find($this->property);

            $propertyHeader = $this->generatePropertyHeader($property->name);

            $outputText .= $propertyHeader;

            $tenancyAgreements = Property::find($this->property)->tenancyAgreements()->get();
            foreach ($tenancyAgreements as $tenancyAgreement){
                $row = $this->generateSingleStatementOfAccount($tenancyAgreement);

                $outputText .= $row['rowContentHtml'];
                $propertyTotalDue += $row['pendingPayments']['total_due'] ?? 0;
                $propertyOneToThirtyPastDue += $row['pendingPayments']['zero_to_thirty_days'] ?? 0;
                $propertyThirtyOneToSixtyPastDue += $row['pendingPayments']['thirty_one_to_sixty_days'] ?? 0;
                $propertySixtyOneToNinetyPastDue += $row['pendingPayments']['sixty_one_to_ninety_days'] ?? 0;
                $propertyOverNinetyPastDue += $row['pendingPayments']['over_ninety_days'] ?? 0;
            }

            $propertyFooter = $this->generatePropertyFooter(
                $property->name,
                $propertyTotalDue,
                $propertyOneToThirtyPastDue,
                $propertyThirtyOneToSixtyPastDue,
                $propertySixtyOneToNinetyPastDue,
                $propertyOverNinetyPastDue
            );

            $outputText .= $propertyFooter;
        }else{
            foreach (Property::all() as $property){
                $propertyTotalDue = 0;
                $propertyOneToThirtyPastDue = 0;
                $propertyThirtyOneToSixtyPastDue = 0;
                $propertySixtyOneToNinetyPastDue = 0;
                $propertyOverNinetyPastDue = 0;

                $propertyHeader = $this->generatePropertyHeader($property->name);

                $outputText .= $propertyHeader;

                foreach ($property->tenancyAgreements()->get() as $tenancyAgreements){
                    $row = $this->generateSingleStatementOfAccount($tenancyAgreements);

                    $outputText .= $row['rowContentHtml'];
                }

                $propertyTotalDue += $row['pendingPayments']['total_due'];
                $propertyOneToThirtyPastDue += $row['pendingPayments']['zero_to_thirty_days'] ?? 0;
                $propertyThirtyOneToSixtyPastDue += $row['pendingPayments']['thirty_one_to_sixty_days'] ?? 0;
                $propertySixtyOneToNinetyPastDue += $row['pendingPayments']['sixty_one_to_ninety_days'] ?? 0;
                $propertyOverNinetyPastDue += $row['pendingPayments']['over_ninety_days'] ?? 0;

                $propertyFooter = $this->generatePropertyFooter(
                    $property->name,
                    $propertyTotalDue,
                    $propertyOneToThirtyPastDue,
                    $propertyThirtyOneToSixtyPastDue,
                    $propertySixtyOneToNinetyPastDue,
                    $propertyOverNinetyPastDue
                );

                $outputText .= $propertyFooter;
            }
        }


        // generate report
        $detailsArray = [
//            'customerName' => $unitName.' '.$tenancyAgreement->tenant->name,
//            'propertyName' => $propertyName,
            'tableHeaderHTML' => $this->generateTableHeader(),
            'dateGenerated'=> Carbon::now()->format('M j, Y'),
            'logoUrl'=>'file://'.getcwd().'/images/hamud_top_doc_logo.png',
            'amountDue' => number_format(0,2),
            'amountEnc' => number_format(0,2),
            'reportContentItemsHTML' => $outputText,
        ];

        $content = File::get(resource_path('documents/templates/ageing-summary-report-output-document.html'));

        foreach ($detailsArray as $key => $value) {
            $content = str_replace("@#$key", $value, $content);
        }

        $pdfName = "Ageing Summary Report".
            '_as_of_' .
            now()->format('F j, Y h:i:s');

        // get the path but without the clatter file system
        $pdfPath = Storage::path('ageing_summary_reports') . '/' . $pdfName . '.pdf';

//            Storage::url($pdfPath);

//            Storage::put($pdfPath, $content);
        $snappy = App::make('snappy.pdf');
        $snappy->setOption('enable-local-file-access', true);
        $snappy->setOption('disable-smart-shrinking', false);
        $snappy->setOption('margin-bottom', '1in');
        $snappy->setOption('margin-left', '1in');
        $snappy->setOption('margin-right', '1in');
        $snappy->setOption('margin-top', '1in');
        $snappy->setOption('orientation', 'landscape');
//            $snappy->generateFromHtml($content, Storage::url($pdfPath));
//            Pdf::generateFromHtml($content, Storage::url($pdfPath));
        $snappy->generateFromHtml($content, $pdfPath);

        // trigger download of the file then delete it
        // this one below is not downloading
        $this->statementPath = $pdfPath;
//        return response()->download($pdfPath,"Ageing summary report as at ".now()->format('F j, Y h:1'),$headers);
    }

    public function displayErrorNotification($message = "Report generation failed"): void
    {
        Notification::make()
            ->title($message)
            ->danger()
            ->send();
    }

    private function generatePropertyHeader($propertyName)
    {
        return '
            <tr style="height: 30px;">
                <td class="cell_property_header" colspan="15">'.ucwords($propertyName).'</td>
            </tr>';
    }

    private function generatePropertyFooter($propertyName,$totalDue,$oneToThirtyPastDue,$thirtyOneToSixtyPastDue,$sixtyOneToNinetyPastDue,$overNinetyPastDue)
    {
        $tableFooterHtml = '
            <tr style="height: 30px;">
                <td class="cell_property_header" colspan="5"> Total '.$propertyName.'</td>';

        if ($this->zero_to_thirty_days){
            $tableFooterHtml .= '<td class="cell_property_footer" colspan="1">'.number_format($oneToThirtyPastDue,2).'</td>';
        }

        if ($this->thirty_one_to_sixty_days){
            $tableFooterHtml .= '<td class="cell_property_footer" colspan="2">'.number_format($thirtyOneToSixtyPastDue,2).'</td>';
        }

        if ($this->sixty_one_to_ninety_days){
            $tableFooterHtml .= '<td class="cell_property_footer" colspan="3">'.number_format($sixtyOneToNinetyPastDue,2).'</td>';
        }

        if ($this->over_ninety_days){
            $tableFooterHtml .= '<td class="cell_property_footer" colspan="2">'.number_format($overNinetyPastDue,2).'</td>';
        }

        $tableFooterHtml .= '<td class="cell_property_footer" colspan="2">'.number_format($totalDue,2).'</td> </tr>';

        return $tableFooterHtml;
    }

    private function generateTableHeader()
    {
        $tableHeaderHtml = '
            <tr style="height: 30px;">
                <td colspan="1"></td>
                <td colspan="4"></td>';

        if ($this->zero_to_thirty_days){
            $tableHeaderHtml .= '<td class="cell_row_header" colspan="1">0-30 days</td>';
        }

        if ($this->thirty_one_to_sixty_days){
            $tableHeaderHtml .= '<td class="cell_row_header" colspan="2">31-60 days</td>';
        }

        if ($this->sixty_one_to_ninety_days){
            $tableHeaderHtml .= '<td class="cell_row_header" colspan="3">61-90 days</td>';
        }

        if ($this->over_ninety_days){
            $tableHeaderHtml .= '<td class="cell_row_header" colspan="2">Over 90 days</td>';
        }

        $tableHeaderHtml .= '<td class="cell_row_header" colspan="2">Total Due</td> </tr>';

        return $tableHeaderHtml;
    }

    private function generateSingleStatementOfAccount($tenancyAgreement)
    {
        // get all invoices and convert to array
        $invoices = Invoice::query()
            ->where('tenancy_agreement_id', '=', $tenancyAgreement->id)
            ->orderBy('created_at', 'desc')
            ->select(['id', 'invoice_for_month as transaction_date','invoice_due_date'])
            ->selectRaw('concat("INV #", id,". Due on ", TO_CHAR(invoice_for_month,"Mon DD, YYYY")) as transaction, concat("invoice") as transaction_type')
            ->get(['amount','unpaid_amount'])
            ->toArray();

        $current = 0;
        $oneToThirtyPastDue = 0;
        $thirtyOneToSixtyPastDue = 0;
        $sixtyOneToNinetyPastDue = 0;
        $overNinetyPastDue = 0;
        // iterate over the invoices obtaining the current, 1-30, 31-60, 61-90, over 90
        foreach ($invoices as $invoice) {
            $invoiceDueDate = Carbon::createFromFormat('Y-m-d',$invoice['invoice_due_date']);
            $daysDifference = $invoiceDueDate->diffInDays(Carbon::now());
            if ($daysDifference > 90){
                $overNinetyPastDue += $invoice['amount'];
            } elseif ($daysDifference > 60){
                $sixtyOneToNinetyPastDue += $invoice['amount'];
            } elseif ($daysDifference > 30){
                $thirtyOneToSixtyPastDue += $invoice['amount'];
            } elseif ($daysDifference > 0 ){
                $oneToThirtyPastDue += $invoice['amount'];
            } elseif ($daysDifference == 0){
                $current += $invoice['amount'];
            }
        }

        $totalDue = 0;
        $pendingPayments = [];

        $rowContentHtml  = '
            <tr style="height: 30px;">
                <td class="details_header_cell_for_statement_summary" colspan="1">'.$tenancyAgreement->unit->name.'</td>
                <td class="details_header_cell_for_statement_summary" colspan="4">'.$tenancyAgreement->tenant->name.'</td>';

        if ($this->zero_to_thirty_days){
            $rowContentHtml .= '<td class="table_cell_for_statement_summary" colspan="1">'.number_format($oneToThirtyPastDue,2).'</td>';
            $totalDue += $oneToThirtyPastDue;
            $pendingPayments['zero_to_thirty_days'] = $oneToThirtyPastDue;
        }
        if ($this->thirty_one_to_sixty_days){
            $rowContentHtml .= '<td class="table_cell_for_statement_summary" colspan="2">'.number_format($thirtyOneToSixtyPastDue,2).'</td>';
            $totalDue += $thirtyOneToSixtyPastDue;
            $pendingPayments['thirty_one_to_sixty_days'] = $thirtyOneToSixtyPastDue;
        }
        if ($this->sixty_one_to_ninety_days){
            $rowContentHtml .= '<td class="table_cell_for_statement_summary" colspan="3">'.number_format($sixtyOneToNinetyPastDue,2).'</td>';
            $totalDue += $sixtyOneToNinetyPastDue;
            $pendingPayments['sixty_one_to_ninety_days'] = $sixtyOneToNinetyPastDue;
        }
        if ($this->over_ninety_days){
            $rowContentHtml .= '<td class="table_cell_for_statement_summary" colspan="2">'.number_format($overNinetyPastDue,2).'</td>';
            $totalDue += $overNinetyPastDue;
            $pendingPayments['over_ninety_days'] = $overNinetyPastDue;
        }

        $rowContentHtml .= '<td class="table_cell_for_statement_summary" colspan="2">'.number_format($totalDue,2).'</td> </tr>';
        $pendingPayments['total_due'] = $totalDue;


        return [
            'rowContentHtml' => $rowContentHtml,
            'pendingPayments' => $pendingPayments
        ];
    }
}
